import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'hotelRating',
  type: 'object',
  title: 'hotelRating',
  description:
    'Rating for HOTEL (0–10 scale; 0 = Not available for Gym, Pool, Internet)',
  fieldsets: [{ name: 'social', title: 'Give a rating 0–10 for each item' }],
  options: {
    collapsible: true,
    collapsed: false,
    columns: 3,
  },
  initialValue: {
    Bed_Comfort: 6,
    Gym: 0,
    Internet_Speed: 0,
    Location: 6,
    Pool: 0,
    Room_Amenities: 6,
    Room_Cleanliness: 6,
    Service: 6,
    Value: 6,
  },
  fields: [
    defineField({
      title: 'Location of Hotel',
      name: 'Location',
      type: 'number',
      validation: (Rule) => Rule.required().min(0).max(10),
      initialValue: 6,
    }),
    defineField({
      title: 'Room Cleanliness',
      name: 'Room_Cleanliness',
      type: 'number',
      validation: (Rule) => Rule.required().min(0).max(10),
      initialValue: 6,
    }),
    defineField({
      title: 'Hotel Service',
      name: 'Service',
      type: 'number',
      validation: (Rule) => Rule.required().min(0).max(10),
      initialValue: 6,
    }),
    defineField({
      title: 'Bed Comfort',
      name: 'Bed_Comfort',
      type: 'number',
      validation: (Rule) => Rule.required().min(0).max(10),
      initialValue: 6,
    }),
    defineField({
      title: 'Internet Speed',
      description: 'Set to 0 if there is no internet',
      name: 'Internet_Speed',
      type: 'number',
      validation: (Rule) => Rule.required().min(0).max(10),
      initialValue: 0,
    }),
    defineField({
      title: 'Room Amenities (TV, Coffee machine etc.)',
      name: 'Room_Amenities',
      type: 'number',
      validation: (Rule) => Rule.required().min(0).max(10),
      initialValue: 6,
    }),
    defineField({
      title: 'Hotel Gym',
      description: 'Set to 0 if there is no gym',
      name: 'Gym',
      type: 'number',
      validation: (Rule) => Rule.required().min(0).max(10),
      initialValue: 0,
    }),
    defineField({
      title: 'Hotel Pool',
      description: 'Set to 0 if there is no pool',
      name: 'Pool',
      type: 'number',
      validation: (Rule) => Rule.required().min(0).max(10),
      initialValue: 0,
    }),
    defineField({
      title: 'Hotel Value',
      name: 'Value',
      type: 'number',
      validation: (Rule) => Rule.required().min(0).max(10),
      initialValue: 6,
    }),
  ],
})
